image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - pwd
    - ls -l
    - cd RoomApps
    - ls
    - mvn install 
    - cd RoomStatus
    - docker build -t ***REMOVED***:9002/roomstatus ./RoomStatus
    - docker build -t ***REMOVED***:9002/roomstatus ./RoomWorker
    - docker build -t ***REMOVED***:9002/roomstatus ./RoomObserver
    - docker login ***REMOVED***:9002 -u sascha -p ***REMOVED***
    - docker push ***REMOVED***:9002/roomstatus
    - docker push ***REMOVED***:9002/roomworker
    - docker push ***REMOVED***:9002/roomobserver