image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - pwd
    - ls -l
    - cd RoomApps
    - ls
    - mvn install
    - docker login localhost:9002 -u sascha -p ***REMOVED***
    - docker build -t localhost:9002/roomstatus RoomStatus
    - docker build -t localhost:9002/roomworker RoomWorker
    - docker build -t localhost:9002/roomobserver RoomObserver
    - docker push localhost:9002/roomstatus
    - docker push localhost:9002/roomworker
    - docker push localhost:9002/roomobserver