name: Build Docker Temperature Backend
on: [push]
jobs:
  Build_Backend:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.PAT_TOKEN }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/alexanderjuhn/github-actions/dispatches --data '{"event_type": "build_application"}'